version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vol12_server
    ports:
      - "5411:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
